
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: energy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1303
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Porta externa:interna

  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: