# Generated by Django 5.2.1 on 2025-05-17 03:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ambiente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('verde', 'Verde'), ('amarela', 'Amarela'), ('vermelha1', 'Vermelha - Patamar 1'), ('vermelha2', 'Vermelha - Patamar 2')], max_length=10, unique=True, verbose_name='Cor da Bandeira')),
                ('valor_adicional', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00000'))], verbose_name='Valor Adicional (R$/kWh)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Bandeira Tarifária',
                'verbose_name_plural': 'Bandeiras Tarifárias',
                'ordering': ['-vigente', 'cor'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TarifaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_consumo', models.CharField(choices=[('ate_30', 'Até 30 kWh/mês'), ('31_a_100', '31 a 100 kWh/mês'), ('101_a_220', '101 a 220 kWh/mês'), ('acima_220', 'Acima de 220 kWh/mês')], max_length=20, unique=True, verbose_name='Faixa de Consumo')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto Percentual (%)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tarifa Social',
                'verbose_name_plural': 'Tarifas Sociais',
                'ordering': ['faixa_consumo'],
            },
        ),
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aparelho')),
                ('potencia_watts', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Potência (Watts)')),
                ('tempo_uso_diario_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tempo de Uso Diário (horas)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparelhos', to='core.ambiente', verbose_name='Ambiente')),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparelhos', to='core.bandeira', verbose_name='Bandeira Tarifária')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparelhos', to='core.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Aparelho',
                'verbose_name_plural': 'Aparelhos',
                'ordering': ['-data_cadastro', 'ambiente', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo (kWh)')),
                ('custo_normal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Normal (R$)')),
                ('custo_social', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Social (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.ambiente', verbose_name='Ambiente')),
                ('aparelhos', models.ManyToManyField(related_name='historico', to='core.aparelho', verbose_name='Aparelhos')),
            ],
            options={
                'verbose_name': 'Histórico de Consumo',
                'verbose_name_plural': 'Históricos de Consumo',
                'ordering': ['-data', 'ambiente'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kwh', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='Valor por kWh (R$)')),
                ('valor_bandeira_verde', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=6, verbose_name='Adicional Bandeira Verde (R$)')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa', to='core.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['estado__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='aparelho',
            index=models.Index(fields=['data_cadastro'], name='core_aparel_data_ca_6f1b14_idx'),
        ),
        migrations.AddIndex(
            model_name='aparelho',
            index=models.Index(fields=['ambiente'], name='core_aparel_ambient_9f5b23_idx'),
        ),
        migrations.AddIndex(
            model_name='aparelho',
            index=models.Index(fields=['estado'], name='core_aparel_estado__38cd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='aparelho',
            index=models.Index(fields=['bandeira'], name='core_aparel_bandeir_649703_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoconsumo',
            index=models.Index(fields=['-data'], name='core_histor_data_e7da40_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoconsumo',
            index=models.Index(fields=['ambiente'], name='core_histor_ambient_81ba58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicoconsumo',
            unique_together={('data', 'ambiente')},
        ),
    ]
