# Generated by Django 5.2.1 on 2025-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bandeira_options_remove_bandeira_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('bandeira', models.CharField(max_length=50)),
                ('tarifa_social', models.BooleanField(default=False)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
