# Generated by Django 5.2.1 on 2025-05-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumomensal_delete_contadorenergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_extraido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_corrigido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_social', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='leituras_imagens/')),
                ('consumo_entre_leituras', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bandeira')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
            ],
        ),
    ]
