# Generated by Django 5.2.1 on 2025-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leituraocr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraocr',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
