# Generated by Django 5.2.1 on 2025-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_leituraocr_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraocr',
            name='imagem',
            field=models.ImageField(upload_to='leituras_imagens/'),
        ),
    ]
