# Generated by Django 5.2.1 on 2025-05-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
